apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: icgroup
  labels:
    env: prod
type: Opaque
data:
  postgres-db: cG9zdGdyZXM=
  postgres-user: b2Rvbw==
  postgres-password: b2Rvbw==
